/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 temple.glb ---transform
Author: Mark A93 (https://sketchfab.com/marka93)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/temple-d45c2fea09ec47c0938d81ae477c3f7f
Title: Temple
*/

import { useBox } from '@react-three/cannon';
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Temple(props) {
  

  const { nodes, materials } = useGLTF('/models/temple-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Temple001_Temple_0.geometry} material={materials.Temple} position={[-15.611, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={2.668} />
    </group>
  )
}

useGLTF.preload('/temple-transformed.glb')
